-- Create table for NBA (Next Best Action) decisions
create table if not exists nba_decisions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  patient_id uuid not null,
  
  -- The ID of the original suggestion (if this is an edit)
  original_action_id text,
  
  -- The ID of the action as decided by the clinician (may differ from original if edited)
  action_id text not null,
  action_type text not null,
  category text,
  rationale text,
  triggering_facts jsonb,
  knowledge_artifacts_used text[],
  confidence_or_strength numeric,
  
  clinician_disposition text not null, -- 'accepted', 'rejected', 'edited'
  disposition_reason text,
  metadata jsonb,
  session_id uuid
);

-- Enable Row Level Security (RLS)
alter table nba_decisions enable row level security;

-- Create policy to allow all operations for authenticated users (or anon for this demo)
create policy "Enable all access for all users" on nba_decisions
  for all using (true) with check (true);

