-- Create table for NBA suggestions (the AI's output)
create table if not exists nba_suggestions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  patient_id uuid not null,
  module_id text not null,
  action_id text not null unique, -- The unique ID from the reasoning engine
  title text not null,
  description text not null,
  rationale text,
  triggering_facts jsonb,
  knowledge_artifacts_used text[],
  confidence_or_strength numeric,
  status text not null default 'pending', -- 'pending', 'accepted', 'rejected', 'edited'
  session_id uuid
);

-- Enable RLS
alter table nba_suggestions enable row level security;

-- Create policy
create policy "Enable all access for all users" on nba_suggestions
  for all using (true) with check (true);

-- Create table for NBA decisions (the clinician's response)
create table if not exists nba_decisions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  patient_id uuid not null,
  suggestion_id bigint references nba_suggestions(id),
  
  -- The final action (may differ from original if edited)
  action_id text not null,
  original_action_id text,
  action_type text not null,
  category text,
  rationale text,
  triggering_facts jsonb,
  knowledge_artifacts_used text[],
  confidence_or_strength numeric,
  
  clinician_disposition text not null, -- 'accepted', 'rejected', 'edited'
  disposition_reason text,
  metadata jsonb,
  session_id uuid
);

-- Enable RLS
alter table nba_decisions enable row level security;

-- Create policy
create policy "Enable all access for all users" on nba_decisions
  for all using (true) with check (true);

-- Create index for faster lookup
create index if not exists idx_nba_suggestions_patient_id on nba_suggestions(patient_id);
create index if not exists idx_nba_decisions_suggestion_id on nba_decisions(suggestion_id);
create index if not exists idx_nba_decisions_patient_id on nba_decisions(patient_id);
